# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honey < Formula
  desc "DevOps tool to help find an instance in sea of clouds."
  homepage "https://github.com/shareed2k/honey"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shareed2k/honey/releases/download/v0.1.0/honey_Darwin_x86_64.zip"
    sha256 "438bba72b396cc2dcf80fbee93d3d26d2e22b4dcbac37fe82543ab391a4ffd85"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/shareed2k/honey/releases/download/v0.1.0/honey_Linux_x86_64.zip"
    sha256 "fea4c2988b82782a6f47fd8fd09ce00bc3bca3f5d42fbda28a73c5df1239d9d2"
  end

  def install
    bin.install "honey"
  end
end
