# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honey < Formula
  desc "DevOps tool to help find an instance in sea of clouds."
  homepage "https://github.com/shareed2k/honey"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shareed2k/honey/releases/download/v0.1.1/honey_Darwin_x86_64.zip"
    sha256 "ff09eede3bc41325b1f0cf30894bed42779b9336fbeccbf6749c7179e0752c7a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/shareed2k/honey/releases/download/v0.1.1/honey_Linux_x86_64.zip"
    sha256 "658eea7e2e895599ccc556331929523c08d4f9317062fa7874aab34851e943f2"
  end

  def install
    bin.install "honey"
  end
end
