# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honey < Formula
  desc "DevOps tool to help find an instance in sea of clouds."
  homepage "https://github.com/bringg/honey"
  version "0.1.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bringg/honey/releases/download/v0.1.6/honey_Darwin_x86_64.zip"
    sha256 "180793e3400a569383cfa241733ecbb8838171bc62ac9dbfd711d5e9c2e0f6ea"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bringg/honey/releases/download/v0.1.6/honey_Linux_x86_64.zip"
    sha256 "e379230655772a03476a6a22102d76ad2b6c8efdd644204d7e276de642334fce"
  end

  def install
    bin.install "honey"
  end
end
